### PR TITLE
Added complete support for iOS.

### PR DESCRIPTION
**Pull request by jigarfumakiya**
Hello @CaiJingLong 

This is PR suggest below changes.

1. Added support for Twitter.
2. Added support for Facebook.
3. Fixed bugs in Whatsapp.
4. Upgrade example to null safety.
5. Updated readme

Can you please take look at all the changes and let me know if require any changes or you want to discuss anything.

Note-:Some might be breaking changes.

Let me know
Jigar

### CODE REVIEW

**Comment by jigarfumakiya** [comment]
Hey @lizhuoyuan 
Did you release this version on pub or not?

Also, I have some plans for this plugin for adding multiple new features.
I like to be a co-contributor of the packages.

Let me know what you think.
Thanks

**Comment by lizhuoyuan** [comment]
@jigarfumakiya 
Thank you for your contribution, I would love to have someone willing to work hard for this, which will help many people.
I am going to release it after the test is correct, and tomorrow at the latest.

**Comment by jigarfumakiya** [comment]
Perfect @lizhuoyuan

**Comment by lizhuoyuan** [comment]
Hey, bro.
I have a question about sharing pictures on whatsapp.
```dart
/// @parm imageUrl is local image
  Future<String?> shareToWhatsApp({String msg = '', String imageUrl = ''}) 
```
The parameter here refers to the local path, or the image URL, or byte, base64?

**Comment by jigarfumakiya** [comment]
This refers to the local image URL. As of now, we don't have support base64.
Will add it soon.

**Comment by lizhuoyuan** [comment]
So it is a path to a local image，right？

**Comment by jigarfumakiya** [comment]
Yes, It's a path to a local image.

**Comment by lizhuoyuan** [comment]
When I want to share pictures to whatsapp, it always fails and returns false.
I saved a picture from elsewhere to the phone, the following is the path：
/var/mobile/Containers/Data/Application/3C79084F-F2C6-410C-9D1A-FD894122DE45/Documents/deer_test_share_2021-08-12 16:18:31.930366.png

**Comment by jigarfumakiya** [comment]
@lizhuoyuan 
Will debug it later today.
Can you please send me which device and model?
Thanks

**Comment by lizhuoyuan** [comment]
iphone X 
os version: 14.4.2

**Comment by jigarfumakiya** [comment]
Thanks
Let me know if you find any other issues

**Comment by jigarfumakiya** [comment]
Hey @lizhuoyuan 

So I have done some debugging with my iPhone 11 and os version: 14.4.2 same as yours.
I am getting the below error and Apparently, this is from WhatsApp side you can  read it here-:https://stackoverflow.com/questions/36603921/this-item-cannot-be-shared-please-select-a-different-item-whatsapp-ios-share

Here is the image 

IMG_3ACD512C01B1-1


I have pick images from the camera as well as photos.
Let me know what is the response you getting

**Comment by jigarfumakiya** [comment]
Hey @lizhuoyuan 
I have done some debugging.
I am able to go to WhatsApp share but there is some issue going on maybe on WhatsApp that says This item can not be shared

Here is the image

IMG_3ACD512C01B1-1

But Plugin successfully sending users to WhatsApp App.I am not able to reproduce the issue as suggested

Let me know what is error you get.

**Comment by armandojimenez** [comment]
This did not work for me, it does not share directly to whatsapp, it creates a temp file and open the native bottom sheet

**Comment by jigarfumakiya** [comment]
Yes, it's correct because WhatsApp doesn't allow direct picture sharing in IOS due to security reasons.
You can read more if you want here-:https://faq.whatsapp.com/iphone/how-to-link-to-whatsapp-from-a-different-app/?lang=en

**Comment by lizhuoyuan** [comment]
@jigarfumakiya  I have added permissions to you, can you see if you can modify the code directly

**Comment by jigarfumakiya** [comment]
@lizhuoyuan 
 we can do nothing here.
As @armandojimenez said it crate the temp file and opens the bottom sheet so the plugin working as expected.
As I said before Whats doesn't allow direct sharing you read more on their official doc.

**Pull request merged**
