### PR TITLE
Added iOS support for WhatsApp and System share.

### PR DESCRIPTION
**Pull request by jigarfumakiya**
Hello @hiteshjoshi @lizhuoyuan 

Hope you all doing well.

This is PR suggest below changes.

1. Upgrade the project to swift support.
2. Added support for WhatsApp for ios.
3. Added support for system share for ios.

Can you please take look at all the changes and let me know if require any changes or you want to discuss anything.

Note-:I am currently working on Facebook and Twitter support will send a new PR soon.

Let me know
Jigar

### CODE REVIEW

**Comment by lizhuoyuan** [comment]
thank you~

**Comment by jigarfumakiya** [comment]
Your welcome.
I Will add other support then will update the readme soon.

**Comment by gkmuhannad** [comment]
WhatsApp msg in ios always "hello" why??

**Comment by jigarfumakiya** [comment]
#43 
@gkmuhannad  Fixed most of the bugs here.
Added complete support for ios.

**Pull request merged**
